spring:
  application:
    name: asset-management-bridge

  datasource:
    url: jdbc:postgresql://localhost:5432/TID_Asset_Management_DB
    username: postgres
    password: Pheaktra123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
      - classpath:db/seeder
    
springdoc:
  swagger-ui:
    path: /api  # Changes the access path to http://localhost:8080/api
    operations-sorter: alpha  # Sorts endpoints alphabetically for better scannability
    tags-sorter: alpha # Sorts the tags (Asset, User, etc.) alphabetically
  api-docs:
    path: /api-docs # Path for the raw JSON documentation used by other tools

server:
  port: 8080

jwt:
  secret: hq3qG2Hj4M5vF7bN8kL9sP1hT4xD6rW8yB2cZ5eV9tI1oU3mK6nA8sJ0gR3yF7v # Replace with a strong, completely secure secret
  expiration: 86400000 # 24 hours in milliseconds